spring:
  application:
    name: limits

  flyway:
    user: "postgres"
    password: ${POSTRGRE_PWD}
    url: "jdbc:postgresql://localhost:5433/test_pro6"

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

app:
  datasource:
      classname: "org.postgresql.ds.PGSimpleDataSource"
      servername: "localhost"
      databaseName: "test_pro6"
      portnumber: "5433"
      user: "tst_user"
      password: "tst_pwd"

logging:
  level:
    org.springframework.web: debug
    org.apache: debug
    org.flywaydb: debug